
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-01
owner: ucsb-cs156-s25
repo_name: team01-s25-01
pull_requests: [{"author":{"id":"U_kgDOCML-SQ","is_bot":false,"login":"alecsekimoto1","name":""},"headRefName":"01-delete-for-recommendationrequest-table","number":49,"title":"as - delete for recommendationrequest table","url":"https://github.com/ucsb-cs156-s25/team01-s25-01/pull/49"},{"author":{"id":"U_kgDOCML-SQ","is_bot":false,"login":"alecsekimoto1","name":""},"headRefName":"01-put-for-recommendationrequest-table","number":48,"title":"as - put for recommendationrequest table","url":"https://github.com/ucsb-cs156-s25/team01-s25-01/pull/48"},{"author":{"id":"U_kgDOCML-SQ","is_bot":false,"login":"alecsekimoto1","name":""},"headRefName":"01-RecommendationRequest-get-by-id","number":47,"title":"as - add GET by id for recommendation requests","url":"https://github.com/ucsb-cs156-s25/team01-s25-01/pull/47"},{"author":{"id":"MDQ6VXNlcjkxNDk3ODM2","is_bot":false,"login":"oscar-luna","name":"Oscar Luna"},"headRefName":"Oscar-MenuItemReview-create-db","number":46,"title":"creates database table for MenuItemReview","url":"https://github.com/ucsb-cs156-s25/team01-s25-01/pull/46"},{"author":{"id":"U_kgDOCML-SQ","is_bot":false,"login":"alecsekimoto1","name":""},"headRefName":"01-RecommendationRequest-create-controller","number":45,"title":"as - recommendation request create controller, add get /all and POST methods","url":"https://github.com/ucsb-cs156-s25/team01-s25-01/pull/45"},{"author":{"id":"U_kgDOCML-SQ","is_bot":false,"login":"alecsekimoto1","name":""},"headRefName":"01-RecommendationRequest-create-db","number":44,"title":"as - create database table for RecommendationRequests","url":"https://github.com/ucsb-cs156-s25/team01-s25-01/pull/44"},{"author":{"id":"U_kgDOBYMMkw","is_bot":false,"login":"EyobTe","name":""},"headRefName":"eyobte-UCSBDiningCommonsMenuItem-create-db","number":43,"title":"eyobte - create database table for UCSBDiningMenuItems","url":"https://github.com/ucsb-cs156-s25/team01-s25-01/pull/43"}]
