
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-01
owner: ucsb-cs156-s25
repo_name: team01-s25-01
pull_requests: [{"author":{"id":"U_kgDOCeRySA","is_bot":false,"login":"llexuan","name":""},"headRefName":"lexuan-delete-for-ucsborganization","number":71,"title":"Lexuan delete for ucsborganization","url":"https://github.com/ucsb-cs156-s25/team01-s25-01/pull/71"},{"author":{"id":"U_kgDOCeRySA","is_bot":false,"login":"llexuan","name":""},"headRefName":"lexuan-ucsborganizaiton-put","number":70,"title":"updated Put method and test","url":"https://github.com/ucsb-cs156-s25/team01-s25-01/pull/70"}]
