
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-01
owner: ucsb-cs156-s25
repo_name: team01-s25-01
pull_requests: [{"author":{"id":"U_kgDOBYMMkw","is_bot":false,"login":"EyobTe","name":""},"headRefName":"eyobte-create-UCSBDiningCommonsMenuItem-controller","number":60,"title":"Eyobte create ucsb dining commons menu item controller","url":"https://github.com/ucsb-cs156-s25/team01-s25-01/pull/60"},{"author":{"id":"U_kgDOB3Dlbw","is_bot":false,"login":"hjin133","name":""},"headRefName":"hj-delete-for-helprequest-table","number":59,"title":"Hj delete for helprequest table","url":"https://github.com/ucsb-cs156-s25/team01-s25-01/pull/59"},{"author":{"id":"U_kgDOB3Dlbw","is_bot":false,"login":"hjin133","name":""},"headRefName":"hj-put-for-helprequest-table","number":57,"title":"Hj put for helprequest table","url":"https://github.com/ucsb-cs156-s25/team01-s25-01/pull/57"},{"author":{"id":"U_kgDOB3Dlbw","is_bot":false,"login":"hjin133","name":""},"headRefName":"hj-helprequest-get-by-id","number":54,"title":"Hj - ad GET by id for help requests","url":"https://github.com/ucsb-cs156-s25/team01-s25-01/pull/54"},{"author":{"id":"U_kgDOB3Dlbw","is_bot":false,"login":"hjin133","name":""},"headRefName":"hj-HelpRequest-create-controller","number":52,"title":"Hj -  help request create controller, add GET /all and POST methods","url":"https://github.com/ucsb-cs156-s25/team01-s25-01/pull/52"},{"author":{"id":"U_kgDOCML-SQ","is_bot":false,"login":"alecsekimoto1","name":""},"headRefName":"01-delete-for-recommendationrequest-table","number":49,"title":"as - delete for recommendationrequest table","url":"https://github.com/ucsb-cs156-s25/team01-s25-01/pull/49"},{"author":{"id":"U_kgDOCML-SQ","is_bot":false,"login":"alecsekimoto1","name":""},"headRefName":"01-put-for-recommendationrequest-table","number":48,"title":"as - put for recommendationrequest table","url":"https://github.com/ucsb-cs156-s25/team01-s25-01/pull/48"},{"author":{"id":"U_kgDOCML-SQ","is_bot":false,"login":"alecsekimoto1","name":""},"headRefName":"01-RecommendationRequest-get-by-id","number":47,"title":"as - add GET by id for recommendation requests","url":"https://github.com/ucsb-cs156-s25/team01-s25-01/pull/47"}]
